window.fichas = [
  {
    "nombre": "钱冰",
    "pinyin": "Qián Bīng",
    "seguidores": 4.99,
    "like": 130,
    "ratio": 26.07,
    "origen": "Chengdu, Sichuan",
    "provincia": "四川省",
    "coord_x": 104.07,
    "coord_y": 30.57,
    "archivo": "Giovanna.jpg",
    "nicho": "Alto impacto",
    "tematica_principal": "lifestyle",
    "Fecha inicio": "",
    "Meses activa": 1513
  },
  {
    "nombre": "隙晓暮",
    "pinyin": "Xì Xiǎo Mù",
    "seguidores": 4.8,
    "like": 67.7,
    "ratio": 14.1,
    "origen": "Sin confirmar",
    "provincia": "北京市",
    "coord_x": 116.4,
    "coord_y": 39.9,
    "archivo": "pipa.jpg",
    "nicho": "Pipa + Hanfu",
    "tematica_principal": "tradicional",
    "Fecha inicio": "",
    "Meses activa": 1513
  },
  {
    "nombre": "Mimi 蛋儿",
    "pinyin": "Mimi Dàn'ér",
    "seguidores": 3.81,
    "like": 70,
    "ratio": 18.38,
    "origen": "Hong Kong",
    "provincia": "香港特别行政区",
    "coord_x": 114.17,
    "coord_y": 22.27,
    "archivo": "mimi.jpg",
    "nicho": "Jazz dance",
    "tematica_principal": "danza",
    "Fecha inicio": "",
    "Meses activa": 1513
  },
  {
    "nombre": "妮老师",
    "pinyin": "Nī Lǎoshī",
    "seguidores": 3.46,
    "like": 110,
    "ratio": 31.84,
    "origen": "Fujian",
    "provincia": "福建省",
    "coord_x": 119.3,
    "coord_y": 26.08,
    "archivo": "bailarina.jpg",
    "nicho": "Humor/Musical 搞怪",
    "tematica_principal": "musica",
    "Fecha inicio": "",
    "Meses activa": 1513
  },
  {
    "nombre": "刘太阳",
    "pinyin": "Liú Tàiyáng",
    "seguidores": 3.29,
    "like": 19.7,
    "ratio": 5.98,
    "origen": "Mongolia Interior",
    "provincia": "内蒙古自治区",
    "coord_x": 111.65,
    "coord_y": 40.82,
    "archivo": "Han Liang.jpg",
    "nicho": "Fitness étnico",
    "tematica_principal": "deportes",
    "Fecha inicio": "",
    "Meses activa": 1513
  },
  {
    "nombre": "飞天小麻花",
    "pinyin": "Fēi Tiān Xiǎo Mhuā",
    "seguidores": 3.18,
    "like": 38.4,
    "ratio": 12.09,
    "origen": "Beijing",
    "provincia": "北京市",
    "coord_x": 116.4,
    "coord_y": 39.9,
    "archivo": "wusguiajpg.jpg",
    "nicho": "Wushu competitivo",
    "tematica_principal": "deportes",
    "Fecha inicio": "",
    "Meses activa": 1513
  },
  {
    "nombre": "郭喆喆",
    "pinyin": "Guō Zhé Zhé",
    "seguidores": 3.1,
    "like": 70,
    "ratio": 22.6,
    "origen": "Chongqing → Wuhan",
    "provincia": "重庆市",
    "coord_x": 106.55,
    "coord_y": 29.56,
    "archivo": "zhezhe.jpg",
    "nicho": "Danza Han/Tang",
    "tematica_principal": "danza",
    "Fecha inicio": "",
    "Meses activa": 1513
  },
  {
    "nombre": "猫姨",
    "pinyin": "Māo Yí",
    "seguidores": 2.92,
    "like": 74.2,
    "ratio": 25.44,
    "origen": "Sichuan",
    "provincia": "四川省",
    "coord_x": 104.07,
    "coord_y": 30.57,
    "archivo": "Miaomiao.jpg",
    "nicho": "Baile urbano 微胖御姐",
    "tematica_principal": "danza",
    "Fecha inicio": "",
    "Meses activa": 1513
  },
  {
    "nombre": "Angier 安琦",
    "pinyin": "Angier Ān Qí",
    "seguidores": 2.8,
    "like": 60,
    "ratio": 21.43,
    "origen": "Liaoning → Kunming",
    "provincia": "辽宁省",
    "coord_x": 123.43,
    "coord_y": 41.8,
    "archivo": "ngjkkm.jpg",
    "nicho": "Baile urbano + hime-cut",
    "tematica_principal": "danza",
    "Fecha inicio": "",
    "Meses activa": 1513
  },
  {
    "nombre": "卢柔伊",
    "pinyin": "Lú Róu Yī",
    "seguidores": 2.607,
    "like": 49.31,
    "ratio": 18.92,
    "origen": "Zhejiang",
    "provincia": "浙江省",
    "coord_x": 120.15,
    "coord_y": 30.28,
    "archivo": "guzheng.jpg",
    "nicho": "Guzheng innovador",
    "tematica_principal": "musica",
    "Fecha inicio": "",
    "Meses activa": 1513
  },
  {
    "nombre": "小白狮杨姐",
    "pinyin": "Xiǎo Bái Shī Yáng Jiě",
    "seguidores": 2.225,
    "like": 22.519,
    "ratio": 10.12,
    "origen": "Shaanxi",
    "provincia": "陕西省",
    "coord_x": 108.94,
    "coord_y": 34.34,
    "archivo": "leon blanco.jpg",
    "nicho": "Danza león blanco",
    "tematica_principal": "danza",
    "Fecha inicio": "",
    "Meses activa": 1513
  },
  {
    "nombre": "墨尔本获宝",
    "pinyin": "Mò'ěrběn Huò Bǎo",
    "seguidores": 1.92,
    "like": 5.68,
    "ratio": 2.96,
    "origen": "Melbourne, Australia",
    "provincia": "上海市",
    "coord_x": 121.47,
    "coord_y": 31.23,
    "archivo": "cocinera.jpg",
    "nicho": "Contenido lifestyle",
    "tematica_principal": "lifestyle",
    "Fecha inicio": "",
    "Meses activa": 1513
  },
  {
    "nombre": "小七。",
    "pinyin": "Xiǎo Qī",
    "seguidores": 1,
    "like": 5.68,
    "ratio": 5.68,
    "origen": "Sichuan",
    "provincia": "四川省",
    "coord_x": 104.07,
    "coord_y": 30.57,
    "archivo": "xiao qi.jpg",
    "nicho": "Contenido lifestyle",
    "tematica_principal": "lifestyle",
    "Fecha inicio": "",
    "Meses activa": 1513
  },
  {
    "nombre": "刘书含",
    "pinyin": "Liú Shūhán",
    "seguidores": 0.992,
    "like": 16.47,
    "ratio": 16.61,
    "origen": "Liaoning",
    "provincia": "辽宁省",
    "coord_x": 123.43,
    "coord_y": 41.8,
    "archivo": "Rose.jpg",
    "nicho": "Ópera moderna 戏腔",
    "tematica_principal": "musica",
    "Fecha inicio": "",
    "Meses activa": 1513
  },
  {
    "nombre": "秋月凉 L",
    "pinyin": "Qiū Yuè Liáng",
    "seguidores": 0.94,
    "like": 15.26,
    "ratio": 16.24,
    "origen": "Sichuan",
    "provincia": "四川省",
    "coord_x": 104.07,
    "coord_y": 30.57,
    "archivo": "liang.jpg",
    "nicho": "Hanfu cinematográfico + cosplay",
    "tematica_principal": "tradicional",
    "Fecha inicio": "",
    "Meses activa": 1513
  },
  {
    "nombre": "刘荇羽",
    "pinyin": "Liú Xíngyǔ",
    "seguidores": 0.562,
    "like": 7.2,
    "ratio": 12.8,
    "origen": "Chongqing, China",
    "provincia": "重庆市",
    "coord_x": 106.55,
    "coord_y": 29.56,
    "archivo": "muralista.jpg",
    "nicho": "Murales en relieve",
    "tematica_principal": "arte",
    "Fecha inicio": "",
    "Meses activa": 1513
  },
  {
    "nombre": "潇洒小柴",
    "pinyin": "Xiāo Sǎ Xiǎo Chái",
    "seguidores": 0.469,
    "like": 6.6,
    "ratio": 14.07,
    "origen": "Hunan",
    "provincia": "湖南省",
    "coord_x": 112.94,
    "coord_y": 28.23,
    "archivo": "pesakawai.jpg",
    "nicho": "Fitness kawaii",
    "tematica_principal": "deportes",
    "Fecha inicio": "",
    "Meses activa": 1513
  },
  {
    "nombre": "小鹤 owo",
    "pinyin": "Xiǎo Hè owo",
    "seguidores": 1.531,
    "like": 20.08,
    "ratio": 13.12,
    "origen": "Xiamen, Fujian",
    "provincia": "福建省",
    "coord_x": 119.3,
    "coord_y": 26.08,
    "archivo": "owo (2).jpg",
    "nicho": "Cosplay + gaming",
    "tematica_principal": "otras",
    "Fecha inicio": "",
    "Meses activa": 1513
  },
  {
    "nombre": "缘妙妙",
    "pinyin": "Yuán Miàomiào",
    "seguidores": 0.003562,
    "like": 0.032,
    "ratio": 8.98,
    "origen": "Anhui",
    "provincia": "安徽省",
    "coord_x": 117.28,
    "coord_y": 31.86,
    "archivo": "miaoma.jpg",
    "nicho": "Pintura budista",
    "tematica_principal": "arte",
    "Fecha inicio": "",
    "Meses activa": 1513
  },
  {
    "nombre": "林苒",
    "pinyin": "Lín Rǎn",
    "seguidores": 0.063,
    "like": 0.247,
    "ratio": 3.92,
    "origen": "Jiangsu",
    "provincia": "江苏省",
    "coord_x": 120,
    "coord_y": 32,
    "archivo": "linra.jpg",
    "nicho": "Hanfu + danza tradicional",
    "tematica_principal": "danza",
    "Fecha inicio": "",
    "Meses activa": 1513
  },
  {
    "nombre": "拿铁笛子",
    "pinyin": "Nátiě Dízǐ",
    "seguidores": 1.975,
    "like": 19.695,
    "ratio": 9.97,
    "origen": "辽宁省",
    "provincia": "辽宁省",
    "coord_x": 121.61,
    "coord_y": 38.91,
    "archivo": "barbiepesas.jpg",
    "nicho": "Fitness IFBB Pro",
    "tematica_principal": "deportes",
    "Fecha inicio": "",
    "Meses activa": 1513
  },
  {
    "nombre": "罗斯露Rose",
    "pinyin": "Luósīlù Rose",
    "seguidores": 1.562,
    "like": 0,
    "ratio": 0,
    "origen": "四川",
    "provincia": "四川",
    "coord_x": 104.06,
    "coord_y": 30.67,
    "archivo": "Rose.jpg",
    "nicho": "Danza latina Olímpica",
    "tematica_principal": "danza",
    "Fecha inicio": "",
    "Meses activa": 1513
  },
  {
    "nombre": "纸鱼",
    "pinyin": "Zhǐ Yú",
    "seguidores": 1.051,
    "like": 13.936,
    "ratio": 13.26,
    "origen": "Zhejiang",
    "provincia": "浙江省",
    "coord_x": 120.15,
    "coord_y": 0.28,
    "archivo": "pezpapel.jpg",
    "nicho": "Modelaje/Cosplay",
    "tematica_principal": "lifestyle",
    "Fecha inicio": "",
    "Meses activa": 1513
  }
];
