const fichas = [
  {
    "Nombre": "钱冰",
    "Pinyin ": "Qián Bīng",
    "seguidores ": 4.99,
    "Like": 130,
    "Ratio ": 26.07,
    "Origen ": "Chengdu, Sichuan",
    "Provincia ": "四川省",
    "Coord x": 104.07,
    "Coord y": 30.57,
    "Archivo ": "Giovanna.jpg",
    "Nicho": "Alto impacto",
    "tematica_principal": "lifestyle"
  },
  {
    "Nombre": "隙晓暮",
    "Pinyin ": "Xì Xiǎo Mù",
    "seguidores ": 4.8,
    "Like": 67.7,
    "Ratio ": 14.1,
    "Origen ": "Sin confirmar",
    "Provincia ": "北京市",
    "Coord x": 116.4,
    "Coord y": 39.9,
    "Archivo ": "pipa.jpg",
    "Nicho": "Pipa + Hanfu",
    "tematica_principal": "tradicional"
  },
  {
    "Nombre": "Mimi 蛋儿",
    "Pinyin ": "Mimi Dàn'ér",
    "seguidores ": 3.81,
    "Like": 70,
    "Ratio ": 18.38,
    "Origen ": "Hong Kong",
    "Provincia ": "香港特别行政区",
    "Coord x": 114.17,
    "Coord y": 22.27,
    "Archivo ": "mimi.jpg",
    "Nicho": "Jazz dance",
    "tematica_principal": "danza"
  },
  {
    "Nombre": "妮老师",
    "Pinyin ": "Nī Lǎoshī",
    "seguidores ": 3.46,
    "Like": 110,
    "Ratio ": 31.84,
    "Origen ": "Fujian",
    "Provincia ": "福建省",
    "Coord x": 119.3,
    "Coord y": 26.08,
    "Archivo ": "bailarina.jpg",
    "Nicho": "Humor/Musical 搞怪",
    "tematica_principal": "musica"
  },
  {
    "Nombre": "刘太阳",
    "Pinyin ": "Liú Tàiyáng",
    "seguidores ": 3.29,
    "Like": 19.7,
    "Ratio ": 5.98,
    "Origen ": "Mongolia Interior",
    "Provincia ": "内蒙古自治区",
    "Coord x": 111.65,
    "Coord y": 40.82,
    "Archivo ": "Han Liang.jpg",
    "Nicho": "Fitness étnico",
    "tematica_principal": "deportes"
  },
  {
    "Nombre": "飞天小麻花",
    "Pinyin ": "Fēi Tiān Xiǎo Mhuā",
    "seguidores ": 3.18,
    "Like": 38.4,
    "Ratio ": 12.09,
    "Origen ": "Beijing",
    "Provincia ": "北京市",
    "Coord x": 116.4,
    "Coord y": 39.9,
    "Archivo ": "wusguiajpg.jpg",
    "Nicho": "Wushu competitivo",
    "tematica_principal": "deportes"
  },
  {
    "Nombre": "郭喆喆",
    "Pinyin ": "Guō Zhé Zhé",
    "seguidores ": 3.1,
    "Like": 70,
    "Ratio ": 22.6,
    "Origen ": "Chongqing → Wuhan",
    "Provincia ": "重庆市",
    "Coord x": 106.55,
    "Coord y": 29.56,
    "Archivo ": "zhezhe.jpg",
    "Nicho": "Danza Han/Tang",
    "tematica_principal": "danza"
  },
  {
    "Nombre": "猫姨",
    "Pinyin ": "Māo Yí",
    "seguidores ": 2.92,
    "Like": 74.2,
    "Ratio ": 25.44,
    "Origen ": "Sichuan",
    "Provincia ": "四川省",
    "Coord x": 104.07,
    "Coord y": 30.57,
    "Archivo ": "Miaomiao.jpg",
    "Nicho": "Baile urbano 微胖御姐",
    "tematica_principal": "danza"
  },
  {
    "Nombre": "Angier 安琦",
    "Pinyin ": "Angier Ān Qí",
    "seguidores ": 2.8,
    "Like": 60,
    "Ratio ": 21.43,
    "Origen ": "Liaoning → Kunming",
    "Provincia ": "辽宁省",
    "Coord x": 123.43,
    "Coord y": 41.8,
    "Archivo ": "ngjkkm.jpg",
    "Nicho": "Baile urbano + hime-cut",
    "tematica_principal": "danza"
  },
  {
    "Nombre": "卢柔伊",
    "Pinyin ": "Lú Róu Yī",
    "seguidores ": 2.607,
    "Like": 49.31,
    "Ratio ": 18.92,
    "Origen ": "Zhejiang",
    "Provincia ": "浙江省",
    "Coord x": 120.15,
    "Coord y": 30.28,
    "Archivo ": "guzheng.jpg",
    "Nicho": "Guzheng innovador",
    "tematica_principal": "musica"
  },
  {
    "Nombre": "小白狮杨姐",
    "Pinyin ": "Xiǎo Bái Shī Yáng Jiě",
    "seguidores ": 2.225,
    "Like": 22.519,
    "Ratio ": 10.12,
    "Origen ": "Shaanxi",
    "Provincia ": "陕西省",
    "Coord x": 108.94,
    "Coord y": 34.34,
    "Archivo ": "leon blanco.jpg",
    "Nicho": "Danza león blanco",
    "tematica_principal": "danza"
  },
  {
    "Nombre": "墨尔本获宝",
    "Pinyin ": "Mò'ěrběn Huò Bǎo",
    "seguidores ": 1.92,
    "Like": 5.68,
    "Ratio ": 2.96,
    "Origen ": "Melbourne, Australia",
    "Provincia ": "上海市",
    "Coord x": 121.47,
    "Coord y": 31.23,
    "Archivo ": "cocinera.jpg",
    "Nicho": "Contenido lifestyle",
    "tematica_principal": "lifestyle"
  },
  {
    "Nombre": "小七。",
    "Pinyin ": "Xiǎo Qī",
    "seguidores ": 1,
    "Like": 5.68,
    "Ratio ": 5.68,
    "Origen ": "Sichuan",
    "Provincia ": "四川省",
    "Coord x": 104.07,
    "Coord y": 30.57,
    "Archivo ": "xiao qi.jpg",
    "Nicho": "Contenido lifestyle",
    "tematica_principal": "lifestyle"
  },
  {
    "Nombre": "刘书含",
    "Pinyin ": "Liú Shūhán",
    "seguidores ": 0.992,
    "Like": 16.47,
    "Ratio ": 16.61,
    "Origen ": "Liaoning",
    "Provincia ": "辽宁省",
    "Coord x": 123.43,
    "Coord y": 41.8,
    "Archivo ": "Rose.jpg",
    "Nicho": "Ópera moderna 戏腔",
    "tematica_principal": "musica"
  },
  {
    "Nombre": "秋月凉 L",
    "Pinyin ": "Qiū Yuè Liáng",
    "seguidores ": 0.94,
    "Like": 15.26,
    "Ratio ": 16.24,
    "Origen ": "Sichuan",
    "Provincia ": "四川省",
    "Coord x": 104.07,
    "Coord y": 30.57,
    "Archivo ": "liang.jpg",
    "Nicho": "Hanfu cinematográfico + cosplay",
    "tematica_principal": "tradicional"
  },
  {
    "Nombre": "刘荇羽",
    "Pinyin ": "Liú Xíngyǔ",
    "seguidores ": 0.562,
    "Like": 7.2,
    "Ratio ": 12.8,
    "Origen ": "Chongqing, China",
    "Provincia ": "重庆市",
    "Coord x": 106.55,
    "Coord y": 29.56,
    "Archivo ": "muralista.jpg",
    "Nicho": "Murales en relieve",
    "tematica_principal": "arte"
  },
  {
    "Nombre": "潇洒小柴",
    "Pinyin ": "Xiāo Sǎ Xiǎo Chái",
    "seguidores ": 0.469,
    "Like": 6.6,
    "Ratio ": 14.07,
    "Origen ": "Hunan",
    "Provincia ": "湖南省",
    "Coord x": 112.94,
    "Coord y": 28.23,
    "Archivo ": "pesakawai.jpg",
    "Nicho": "Fitness kawaii",
    "tematica_principal": "deportes"
  },
  {
    "Nombre": "小鹤 owo",
    "Pinyin ": "Xiǎo Hè owo",
    "seguidores ": 1.531,
    "Like": 20.08,
    "Ratio ": 13.12,
    "Origen ": "Xiamen, Fujian",
    "Provincia ": "福建省",
    "Coord x": 119.3,
    "Coord y": 26.08,
    "Archivo ": "owo (2).jpg",
    "Nicho": "Cosplay + gaming",
    "tematica_principal": "otras"
  },
  {
    "Nombre": "缘妙妙",
    "Pinyin ": "Yuán Miàomiào",
    "seguidores ": 0.003562,
    "Like": 0.032,
    "Ratio ": 8.98,
    "Origen ": "Anhui",
    "Provincia ": "安徽省",
    "Coord x": 117.28,
    "Coord y": 31.86,
    "Archivo ": "miaoma.jpg",
    "Nicho": "Pintura budista",
    "tematica_principal": "arte"
  },
  {
    "Nombre": "林苒",
    "Pinyin ": "Lín Rǎn",
    "seguidores ": 0.063,
    "Like": 0.247,
    "Ratio ": 3.92,
    "Origen ": "Jiangsu",
    "Provincia ": "江苏省",
    "Coord x": 120,
    "Coord y": 32,
    "Archivo ": "linra.jpg",
    "Nicho": "Hanfu + danza tradicional",
    "tematica_principal": "danza"
  },
  {
    "Nombre": "拿铁笛子",
    "Pinyin ": "Nátiě Dízǐ",
    "seguidores ": 1.975,
    "Like": 19.695,
    "Ratio ": 9.97,
    "Origen ": "辽宁省",
    "Provincia ": "辽宁省",
    "Coord x": 121.61,
    "Coord y": 38.91,
    "Archivo ": "barbiepesas.jpg",
    "Nicho": "Fitness IFBB Pro",
    "tematica_principal": "deportes"
  },
  {
    "Nombre": "罗斯露Rose",
    "Pinyin ": "Luósīlù Rose",
    "seguidores ": 1.562,
    "Like": 0,
    "Ratio ": 0,
    "Origen ": "四川",
    "Provincia ": "四川",
    "Coord x": 104.06,
    "Coord y": 30.67,
    "Archivo ": "Rose.jpg",
    "Nicho": "Danza latina Olímpica",
    "tematica_principal": "danza"
  }
