
    "Fecha inicio": 2023,
    "Meses activa": 36
  },
  {
    "nombre": "小鹤 owo",
    "pinyin": "Xiǎo Hè owo",
    "seguidores": 1.531,
    "like": 20.08,
    "ratio": 13.12,
    "origen": "Xiamen, Fujian",
    "provincia": "福建省",
    "coord_x": 119.3,
    "coord_y": 26.08,
    "archivo": "owo (2).jpg",
    "nicho": "Cosplay + gaming",
    "tematica_principal": "otras",
    "Fecha inicio": 2023,
    "Meses activa": 36
  },
  {
    "nombre": "缘妙妙",
    "pinyin": "Yuán Miàomiào",
    "seguidores": 0.003562,
    "like": 0.032,
    "ratio": 8.98,
    "origen": "Anhui",
    "provincia": "安徽省",
    "coord_x": 117.28,
    "coord_y": 31.86,
    "archivo": "miaoma.jpg",
    "nicho": "Pintura budista",
    "tematica_principal": "arte",
    "Fecha inicio": 2023,
    "Meses activa": 36
  },
  {
    "nombre": "林苒",
    "pinyin": "Lín Rǎn",
    "seguidores": 0.063,
    "like": 0.247,
    "ratio": 3.92,
    "origen": "Jiangsu",
    "provincia": "江苏省",
    "coord_x": 120,
    "coord_y": 32,
    "archivo": "linra.jpg",
    "nicho": "Hanfu + danza tradicional",
    "tematica_principal": "danza",
    "Fecha inicio": 2023,
    "Meses activa": 36
  },
  {
    "nombre": "拿铁笛子",
    "pinyin": "Nátiě Dízǐ",
    "seguidores": 1.975,
    "like": 19.695,
    "ratio": 9.97,
    "origen": "辽宁省",
    "provincia": "辽宁省",
    "coord_x": 121.61,
    "coord_y": 38.91,
    "archivo": "barbiepesas.jpg",
    "nicho": "Fitness IFBB Pro",
    "tematica_principal": "deportes",
    "Fecha inicio": 2023,
    "Meses activa": 36
  },
  {
    "nombre": "罗斯露Rose",
    "pinyin": "Luósīlù Rose",
    "seguidores": 1.562,
    "like": 12.31,
    "ratio": 7.89,
    "origen": "四川",
    "provincia": "四川",
    "coord_x": 104.06,
    "coord_y": 30.67,
    "archivo": "Rose.jpg",
    "nicho": "Danza latina Olímpica",
    "tematica_principal": "danza",
    "Fecha inicio": 2023,
    "Meses activa": 36
  },
  {
    "nombre": "纸鱼",
    "pinyin": "Zhǐ Yú",
    "seguidores": 1.051,
    "like": 13.936,
    "ratio": 13.26,
    "origen": "Zhejiang",
    "provincia": "浙江省",
    "coord_x": 120.15,
    "coord_y": 30.28,
    "archivo": "pezpapel.jpg",
    "nicho": "Modelaje/Cosplay",
    "tematica_principal": "lifestyle",
    "Fecha inicio": 2023,
    "Meses activa": 36
  },
  {
    "nombre": "皮卡丘 Ruanm",
    "pinyin": "Pí Kǎ Qiū Ruanm",
    "seguidores": 1.686,
    "like": 26.736,
    "ratio": 15.86,
    "origen": "Jiangsu",
    "provincia": "江苏省",
    "coord_x": 120,
    "coord_y": 32,
    "archivo": "ruanm.jpg",
    "nicho": "Danza",
    "tematica_principal": "danza",
    "Fecha inicio": 2023,
    "Meses activa": 29
  }
];
